// vue/src/components/TextInput.vue
<script setup>
import { onMounted, ref } from 'vue';

defineProps({
    modelValue: {
        type: String,
        required: true,
    },
});

defineEmits(['update:modelValue']);

const input = ref(null);

onMounted(() => {
    if (input.value.hasAttribute('autofocus')) {
        input.value.focus();
    }
});

defineExpose({ focus: () => input.value.focus() });
</script>

<template>
    <input
        class="h-10 p-2 border border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
        :value="modelValue"
        @input="$emit('update:modelValue', $event.target.value)"
        ref="input"
    />
</template>

// react/src/components/TextInput.jsx
const TextInput = ({ inputValue, type, classes, handleChange }) => {
        return (
               <>
                   <input className={classes + " h-10 p-2 border border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"}
                          type={type}
                          value={inputValue}
                          onChange={handleChange}
                   />
               </>
        )
}
export default TextInput
